# Generated by Django 4.2.11 on 2026-05-28 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('ingestion_method', models.CharField(choices=[('CSV', 'CSV File Upload'), ('API', 'API Pull'), ('MANUAL', 'Manual Entry')], default='CSV', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial (some rows failed)'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='emissions.datasource')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct'), ('SCOPE_2', 'Scope 2 — Purchased Electricity'), ('SCOPE_3', 'Scope 3 — Value Chain / Travel')], max_length=10)),
                ('activity_type', models.CharField(choices=[('DIESEL_COMBUSTION', 'Diesel Combustion'), ('NATURAL_GAS', 'Natural Gas Combustion'), ('FUEL_OIL', 'Fuel Oil Combustion'), ('ELECTRICITY_PURCHASED', 'Purchased Electricity'), ('AIR_TRAVEL', 'Air Travel'), ('HOTEL_STAY', 'Hotel Stay'), ('GROUND_TRANSPORT', 'Ground Transport'), ('PROCUREMENT', 'Procurement / Supply Chain')], max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('raw_date', models.CharField(max_length=50)),
                ('normalized_quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=30)),
                ('activity_date', models.DateField()),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('normalized_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('cost_amount', models.FloatField(blank=True, null=True)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('estimated_emission_kgco2e', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_REVIEW', 'Needs Manual Review')], default='PENDING', max_length=15)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.datasource')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='emissions.rawupload')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('UPDATED', 'Record Updated'), ('APPROVED', 'Record Approved'), ('REJECTED', 'Record Rejected'), ('LOCKED', 'Record Locked for Audit'), ('FLAG_CHANGED', 'Suspicious Flag Changed')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'status'], name='emissions_e_organiz_a7c7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope'], name='emissions_e_organiz_cfc59b_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['suspicious_flag'], name='emissions_e_suspici_01aa60_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emissions_e_activit_c89ba8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('organization', 'source_name')},
        ),
    ]
